spring:
  application:
    name: maintenance-query-service

  datasource:
    url: jdbc:mysql://localhost:3306/maintenance_query_es_db?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "root"
    password: "LILOkilomin"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: maintenance-query-service-es
      # Gestion des erreurs via ErrorHandlingDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      # Configuration du delegate (le vrai désérialiseur)
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.autotech.maintenance.*"
        spring.json.use.type.headers: false
        spring.json.remove.type.headers: false

      listener:
        missing-topics-fatal: false

server:
  port: 8082

logging:
  level:
    root: INFO
    com.autotech.maintenance: DEBUG
