spring:
  application:
    name: vehicle-query-service

  datasource:
    url: jdbc:mysql://localhost:3306/vehicle_view_db?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "root"
    password: "LILOkilomin"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: vehicle-query-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.autotech.vehicle.*"
        spring.json.value.default.type: "com.autotech.vehicle.query.messaging.DomainEventEnvelope"
        spring.json.use.type.headers: false
        spring.json.remove.type.headers: false

server:
  port: 8092

logging:
  level:
    root: INFO
    org.springframework.kafka: INFO
    com.autotech.vehicle: DEBUG
