spring:
  application:
    name: maintenance-saga-orchestrator

  datasource:
    url: jdbc:mysql://localhost:3306/maintenance_saga_db?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "root"
    password: "LILOkilomin"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: maintenance-saga-orchestrator
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8095
