spring:
  application:
    name: vehicle-command-service

  datasource:
    url: jdbc:mysql://localhost:3306/vehicle_command_es_db?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "root"
    password: "LILOkilomin"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8091

logging:
  level:
    root: INFO
    com.autotech.vehicle: DEBUG
