spring:
  application:
    name: maintenance-query-service

  datasource:
    url: jdbc:mysql://localhost:3306/maintenance_view_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: "root"
    password: "LILOkilomin"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: maintenance-query-service
      # Gestion des erreurs via ErrorHandlingDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

      # Configuration du delegate (le vrai désérialiseur)
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.autotech.maintenance.*"
        spring.json.value.default.type: "com.autotech.maintenance.query.messaging.DomainEventEnvelope"
        spring.json.use.type.headers: false   # IMPORTANT si le producer n'envoie pas les headers __TypeId__
        spring.json.remove.type.headers: false

      listener:
        missing-topics-fatal: false

server:
  port: 8082
